```yaml
title: Эндокринно-перцептивная дисфория
description: Гипотеза биохимической природы телесного дискомфорта
baseurl: "/epd"
url: "https://alisaversina.github.io"
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-seo-tag
```